[package]
name = "redis-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "^1.44", features = ["full"]}

simple_logger = "^5"
log = "^0.4"

dotenvy = "^0.15"
thiserror = "2.0.12"
anyhow = "1.0.97"
bytes = "1.10.1"
